# Generated by Django 3.2.19 on 2023-06-13 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import econplayground.assignment.custom_storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0095_alter_question_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Untitled', max_length=1024)),
                ('embedded_media', models.TextField(blank=True, default='')),
                ('media_upload', models.FileField(blank=True, null=True, storage=econplayground.assignment.custom_storage.MediaStorage, upload_to='')),
                ('keywords', models.TextField(blank=True, default='')),
                ('prompt', models.TextField(blank=True, default='')),
                ('value', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_question', to='main.graph')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Untitled', max_length=1024)),
                ('published', models.BooleanField(default=False)),
                ('prompt', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohorts', models.ManyToManyField(blank=True, to='main.Cohort')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.question')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.tree')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
