# Generated by Django 3.2.19 on 2023-06-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
