# Generated by Django 3.2.19 on 2023-06-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_step_is_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
