# Generated by Django 3.2.19 on 2023-06-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_step_is_root'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='is_root',
            new_name='is_root_node',
        ),
    ]
