# Generated by Django 3.2.19 on 2023-06-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20230620_1050'),
        ('assignment', '0003_rename_is_root_step_is_root_node'),
    ]

    operations = [
    ]
