# Generated by Django 4.2.2 on 2023-06-27 17:44

from django.db import migrations, models
import django.db.models.deletion
import econplayground.assignment.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_remove_question_graph'),
        ('assignment', '0004_merge_20230621_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='')),
                ('prompt', models.TextField(blank=True, default='')),
                ('media_upload', models.FileField(blank=True, null=True, storage=econplayground.assignment.custom_storage.MediaStorage, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_name', models.CharField(blank=True, default='', max_length=1024)),
                ('assessment_value', models.CharField(blank=True, default='', max_length=1024)),
                ('feedback_fulfilled', models.TextField(blank=True, default='')),
                ('feedback_unfulfilled', models.TextField(blank=True, default='')),
                ('graph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.graph')),
            ],
        ),
        migrations.AddField(
            model_name='step',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.question'),
        ),
    ]
