# Generated by Django 4.2.2 on 2023-06-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_question_step_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignment.question'),
        ),
    ]
