# Generated by Django 4.2.4 on 2023-08-17 18:21

from django.db import migrations, models
import django.db.models.deletion
import econplayground.assignment.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_step_next_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='assessment_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='assessment_value',
        ),
        migrations.RemoveField(
            model_name='question',
            name='feedback_fulfilled',
        ),
        migrations.RemoveField(
            model_name='question',
            name='feedback_unfulfilled',
        ),
        migrations.RemoveField(
            model_name='question',
            name='media_upload',
        ),
        migrations.CreateModel(
            name='AssessmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_name', models.CharField(max_length=1024)),
                ('assessment_value', models.CharField(max_length=1024)),
                ('feedback_fulfilled', models.TextField(blank=True, default='')),
                ('media_fulfilled', models.FileField(blank=True, null=True, storage=econplayground.assignment.custom_storage.MediaStorage, upload_to='')),
                ('feedback_unfulfilled', models.TextField(blank=True, default='')),
                ('media_unfulfilled', models.FileField(blank=True, null=True, storage=econplayground.assignment.custom_storage.MediaStorage, upload_to='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.question')),
            ],
        ),
    ]
