# Generated by Django 4.2.7 on 2023-11-21 18:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_stepresult_scorepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Untitled', max_length=1024)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', max_length=1024), size=None)),
                ('correct', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.question')),
            ],
        ),
    ]
