# Generated by Django 4.2.11 on 2024-04-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0013_stepresult_student_alter_stepresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepresult',
            name='loop',
            field=models.IntegerField(default=0),
        ),
    ]
