# Generated by Django 4.2.15 on 2024-08-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0016_remove_stepresult_loop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
