# Generated by Django 4.2.15 on 2024-08-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0017_alter_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='assessment_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
