version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-patch"]
  - dependency-name: django
    versions:
    - ">= 3.a, < 4"
  - dependency-name: pylint
    versions:
    - 2.6.1
    - 2.7.3
    - 2.8.0
  - dependency-name: astroid
    versions:
    - 2.5.4
    - 2.5.5
  - dependency-name: importlib-metadata
    versions:
    - 3.6.0
    - 3.8.0
    - 3.8.1
    - 3.9.0
    - 3.9.1
    - 4.0.0
  - dependency-name: django-extensions
    versions:
    - 3.1.1.post1
  - dependency-name: faker
    versions:
    - 6.2.0
    - 6.5.1
    - 7.0.0
  - dependency-name: s3transfer
    versions:
    - 0.3.5
  - dependency-name: pillow
    versions:
    - 8.1.1
  - dependency-name: sentry-sdk
    versions:
    - 0.20.0
    - 0.20.1
  - dependency-name: cryptography
    versions:
    - 3.3.2
    - "3.4"
    - 3.4.2
    - 3.4.4
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-patch"]
  - dependency-name: webpack
    versions:
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.0
    - 5.22.0
    - 5.26.0
    - 5.26.1
    - 5.27.0
    - 5.27.1
    - 5.32.0
    - 5.33.2
    - 5.35.0
  - dependency-name: whatwg-fetch
    versions:
    - 3.6.0
