# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graph_type', models.PositiveSmallIntegerField(
                    choices=[
                        (0, 'Demand-Supply Graph'), (1, 'Labor Market'),
                        (2, 'Labor Market (perfectly inelastic)'),
                        (3, 'Cobb-Douglas'),
                        (4, 'Labor Supply'), (5, 'Consumption - Saving'),
                        (6, 'Saving - Investment'), (7, 'Money Market')],
                    default=0)),
                ('line_1_slope', models.DecimalField(
                    decimal_places=2, max_digits=12)),
                ('line_2_slope', models.DecimalField(
                    decimal_places=2, max_digits=12)),
                ('line_1_label', models.TextField(blank=True, null=True)),
                ('line_2_label', models.TextField(blank=True, null=True)),
                ('x_axis_label', models.TextField(blank=True, null=True)),
                ('y_axis_label', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
