# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=5, max_digits=12)),
                ('y', models.DecimalField(decimal_places=5, max_digits=12)),
                ('label', models.TextField()),
                ('is_draggable', models.BooleanField(
                    default=False, help_text='Can a user drag this?')),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('graph_type', models.PositiveSmallIntegerField(
                    choices=[
                        (0, 'Demand-Supply Graph'), (1, 'Labor Market'),
                        (2, 'Labor Market (perfectly inelastic)'),
                        (3, 'Cobb-Douglas'), (4, 'Labor Supply'),
                        (5, 'Consumption - Saving'),
                        (6, 'Saving - Investment'),
                        (7, 'Money Market')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('pos', models.DecimalField(decimal_places=5, max_digits=12)),
                ('label', models.TextField()),
                ('is_draggable', models.BooleanField(
                    default=False, help_text='Can a user drag this?')),
                ('curve', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='main.Curve')),
            ],
        ),
        migrations.AddField(
            model_name='curve',
            name='graph',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='main.Graph'),
        ),
    ]
