# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 19:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaygroundGraph',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(
                    auto_now=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(
                    default={})),
            ],
        ),
        migrations.CreateModel(
            name='ProblemGraph',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(
                    auto_now=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(
                    default={})),
            ],
        ),
        migrations.RemoveField(
            model_name='curve',
            name='graph',
        ),
        migrations.RemoveField(
            model_name='point',
            name='curve',
        ),
        migrations.DeleteModel(
            name='Curve',
        ),
        migrations.DeleteModel(
            name='Graph',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
