# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171121_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_1_decrease_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_1_increase_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_2_decrease_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_2_increase_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
