# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171128_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='display_feedback',
            field=models.BooleanField(default=True),
        ),
    ]
