# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_graph_display_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='line_1_label_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_1_slope_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_2_label_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_2_slope_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='x_axis_label_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='y_axis_label_editable',
            field=models.BooleanField(default=True),
        ),
    ]
