# Generated by Django 2.0 on 2017-12-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_graph_interaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='intersection_horiz_line_label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='intersection_horiz_line_label_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='intersection_label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='intersection_label_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='intersection_vert_line_label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='intersection_vert_line_label_editable',
            field=models.BooleanField(default=True),
        ),
    ]
