# Generated by Django 2.0 on 2017-12-27 15:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20171221_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='cobb_douglas_a',
            field=models.DecimalField(decimal_places=4, default=Decimal('2'), help_text='A = Total factor productivity', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='cobb_douglas_alpha',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.65'), help_text='α = output elasticity of capital', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='cobb_douglas_k',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='K = Capital input', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='cobb_douglas_l',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='L = Labor input', max_digits=12, null=True),
        ),
    ]
