# Generated by Django 2.0.1 on 2018-01-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20171227_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='cobb_douglas_a_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='cobb_douglas_a_name',
            field=models.TextField(default='A'),
        ),
        migrations.AddField(
            model_name='graph',
            name='cobb_douglas_alpha_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='cobb_douglas_alpha_name',
            field=models.TextField(default='α'),
        ),
        migrations.AddField(
            model_name='graph',
            name='cobb_douglas_correct_scenario',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Param 1 (A) increased'), (1, 'Param 1 (A) decreased'), (2, 'Param 2 (K) increased'), (3, 'Param 2 (K) decreased'), (4, 'Param 3 (α) increased'), (5, 'Param 3 (α) decreased'), (6, 'Param 4 (L) increased'), (7, 'Param 4 (L) decreased')], default=0, help_text='Define the correct scenario for this quiz'),
        ),
        migrations.AddField(
            model_name='graph',
            name='cobb_douglas_k_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='cobb_douglas_k_name',
            field=models.TextField(default='K'),
        ),
        migrations.AddField(
            model_name='graph',
            name='cobb_douglas_l_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='cobb_douglas_l_name',
            field=models.TextField(default='L'),
        ),
        migrations.AddField(
            model_name='graph',
            name='cobb_douglas_plot_on_k',
            field=models.BooleanField(default=False, help_text='If enabled, plot the function along param 2 (K) as the X-axis. Otherwise, uses param 4 (L).'),
        ),
    ]
