# Generated by Django 2.0.1 on 2018-01-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180109_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='cobb_douglas_a_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graph',
            name='cobb_douglas_alpha_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graph',
            name='cobb_douglas_k_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graph',
            name='cobb_douglas_l_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graph',
            name='intersection_horiz_line_label_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graph',
            name='intersection_label_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graph',
            name='intersection_vert_line_label_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graph',
            name='line_1_label_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graph',
            name='line_1_slope_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graph',
            name='line_2_label_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graph',
            name='line_2_slope_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graph',
            name='x_axis_label_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graph',
            name='y_axis_label_editable',
            field=models.BooleanField(default=False),
        ),
    ]
