# Generated by Django 2.0.1 on 2018-01-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180111_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graph',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='graph',
            name='cobb_douglas_correct_scenario',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Param 1 (A) increased'), (1, 'Param 1 (A) decreased'), (2, 'Param 2 (K) increased'), (3, 'Param 2 (K) decreased'), (4, 'Param 3 (α) increased'), (5, 'Param 3 (α) decreased'), (6, 'Param 4 (L) increased'), (7, 'Param 4 (L) decreased')], default=0, help_text='Define the correct scenario for this submittable graph.'),
        ),
    ]
