# Generated by Django 2.0.1 on 2018-02-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180131_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='correct_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='incorrect_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
