# Generated by Django 2.0.2 on 2018-02-06 18:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180202_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='alpha',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.3'), max_digits=12),
        ),
    ]
