# Generated by Django 2.0.2 on 2018-02-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20180206_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='line_1_offset_x',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_1_offset_y',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_2_offset_x',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_2_offset_y',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
