# Generated by Django 2.0.2 on 2018-02-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180207_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='display_shadow',
            field=models.BooleanField(default=True),
        ),
    ]
