# Generated by Django 2.0.2 on 2018-02-19 18:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_graph_display_shadow'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='a',
            field=models.DecimalField(decimal_places=4, default=Decimal('3'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='k',
            field=models.DecimalField(decimal_places=4, default=Decimal('2'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='omega',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='r',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='y1',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='y2',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='graph',
            name='graph_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Linear Demand and Supply'), (1, 'Non-Linear Demand and Supply'), (2, 'Labor Market (perfectly inelastic)'), (3, 'Cobb-Douglas'), (4, 'Labor Supply'), (5, 'Consumption - Leisure'), (6, 'Saving - Investment'), (7, 'Money Market')], default=0),
        ),
    ]
