# Generated by Django 2.0.2 on 2018-02-21 15:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20180219_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='a1',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='a1_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='a2',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='a2_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='a3',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='a3_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='a4',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='a4_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='a5',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='a5_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='graph_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Linear Demand and Supply'), (1, 'Non-Linear Demand and Supply'), (2, 'Labor Market (perfectly inelastic)'), (3, 'Cobb-Douglas'), (4, 'Labor Supply'), (5, 'Consumption - Leisure'), (6, 'Saving - Investment'), (7, 'Consumption - Saving')], default=0),
        ),
    ]
