# Generated by Django 2.0.2 on 2018-02-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20180221_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='line_1_offset',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_2_offset',
        ),
    ]
