# Generated by Django 2.0.2 on 2018-02-28 17:01

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20180221_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='JXGLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, help_text='Is this line one or two on the graph?')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Graph')),
            ],
        ),
        migrations.CreateModel(
            name='JXGLineTransformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('x', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('y', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.JXGLine')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='jxgline',
            unique_together={('graph', 'number')},
        ),
    ]
