# Generated by Django 2.0.3 on 2018-03-12 19:18

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20180228_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jxglinetransformation',
            old_name='x',
            new_name='x1',
        ),
        migrations.RenameField(
            model_name='jxglinetransformation',
            old_name='y',
            new_name='x2',
        ),
        migrations.RenameField(
            model_name='jxglinetransformation',
            old_name='z',
            new_name='x3',
        ),
        migrations.AddField(
            model_name='jxglinetransformation',
            name='y1',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='jxglinetransformation',
            name='y2',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='jxglinetransformation',
            name='y3',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='jxglinetransformation',
            name='z1',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='jxglinetransformation',
            name='z2',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='jxglinetransformation',
            name='z3',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='jxgline',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='main.Graph'),
        ),
        migrations.AlterField(
            model_name='jxglinetransformation',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='main.JXGLine'),
        ),
    ]
