# Generated by Django 2.0.3 on 2018-03-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20180312_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='a1_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='graph',
            name='a2_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='graph',
            name='a3_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='graph',
            name='a4_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
