# Generated by Django 2.0.3 on 2018-03-19 16:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20180316_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='line_3_label',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_3_label_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_3_offset_x',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_3_offset_y',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_3_slope',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_3_slope_editable',
            field=models.BooleanField(default=False),
        ),
    ]
