# Generated by Django 2.0.3 on 2018-03-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20180320_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='display_intersection_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graph',
            name='display_intersection_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graph',
            name='display_intersection_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graph',
            name='intersection_2_label',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='intersection_2_label_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graph',
            name='intersection_3_label',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='intersection_3_label_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_1_dashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_1_dashed_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_2_dashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_2_dashed_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_3_dashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_3_dashed_editable',
            field=models.BooleanField(default=False),
        ),
    ]
