# Generated by Django 2.0.4 on 2018-04-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20180403_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='intersection_2_horiz_line_label',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='intersection_2_horiz_line_label_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graph',
            name='intersection_2_vert_line_label',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='intersection_2_vert_line_label_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graph',
            name='intersection_3_horiz_line_label',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='intersection_3_horiz_line_label_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graph',
            name='intersection_3_vert_line_label',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='intersection_3_vert_line_label_editable',
            field=models.BooleanField(default=False),
        ),
    ]
