# Generated by Django 2.0.4 on 2018-04-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20180413_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='a1_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a2_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a3_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a4_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a5_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='cobb_douglas_a_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='cobb_douglas_alpha_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='cobb_douglas_k_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='cobb_douglas_l_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='intersection_2_label_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='intersection_3_label_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='intersection_label_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_1_dashed_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_1_label_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_1_slope_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_2_dashed_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_2_label_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_2_slope_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_3_dashed_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_3_label_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_3_slope_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='x_axis_label_editable',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='y_axis_label_editable',
        ),
    ]
