# Generated by Django 2.0.4 on 2018-04-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20180413_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='interaction_type',
        ),
    ]
