# Generated by Django 2.0.4 on 2018-04-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_graph_interaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='assignment_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Template graph'), (1, 'Labeling'), (2, 'Modification')], default=0),
        ),
    ]
