# Generated by Django 2.0.5 on 2018-05-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_graph_assignment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='cobb_douglas_correct_scenario',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_1_decrease_score',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_1_feedback_decrease',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_1_feedback_increase',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_1_increase_score',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_2_decrease_score',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_2_feedback_decrease',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_2_feedback_increase',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='line_2_increase_score',
        ),
    ]
