# Generated by Django 2.0.5 on 2018-05-31 16:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20180530_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Graph')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('feedback_fulfilled', models.TextField(blank=True, default='')),
                ('feedback_unfulfilled', models.TextField(blank=True, default='')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Assessment')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
