# Generated by Django 2.0.6 on 2018-06-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_assessment_assessmentrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='correct_feedback',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='incorrect_feedback',
        ),
    ]
