# Generated by Django 2.0.6 on 2018-06-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20180620_1407'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentrule',
            unique_together={('assessment', 'name', 'value')},
        ),
    ]
