# Generated by Django 2.0.6 on 2018-06-22 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20180620_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='graph',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Graph'),
        ),
    ]
