# Generated by Django 2.0.6 on 2018-06-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20180626_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='choice',
        ),
    ]
