# Generated by Django 2.0.6 on 2018-06-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_remove_submission_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
