# Generated by Django 2.0.6 on 2018-06-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20180628_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='description',
            new_name='instructions',
        ),
        migrations.AddField(
            model_name='graph',
            name='summary',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
    ]
