# Generated by Django 2.0.6 on 2018-07-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20180629_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graph',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='graph',
            name='order',
            field=models.PositiveIntegerField(
                db_index=True,
                default=555,
                editable=False),
            preserve_default=False,
        ),
    ]
