# Generated by Django 2.0.7 on 2018-07-10 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_create_general_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.Topic'),
        ),
    ]
