# Generated by Django 2.1.7 on 2019-02-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20180813_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='function_choice',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
