# Generated by Django 2.2.3 on 2019-07-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20190711_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Course Title'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'cohort')},
        ),
    ]
