# Generated by Django 2.2.3 on 2019-07-19 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20190717_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='topic',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Topic'),
        ),
    ]
