# Generated by Django 2.2.4 on 2019-08-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20190827_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graph',
            options={'ordering': ('topic__cohort', 'order')},
        ),
    ]
