# Generated by Django 2.2.4 on 2019-09-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20190828_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
