# Generated by Django 2.2.4 on 2019-10-02 15:11

from django.db import migrations


def make_assessments(apps, schema_editor):
    """Make an assessment for each graph that doesn't have one."""
    Graph = apps.get_model('main', 'Graph')
    Assessment = apps.get_model('main', 'Assessment')
    for g in Graph.objects.filter(assessment=None):
        a = Assessment(graph=g)
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_cohort_password'),
    ]

    operations = [
        migrations.RunPython(make_assessments),
    ]
