# Generated by Django 2.2.4 on 2019-10-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20191002_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='is_sample',
            field=models.BooleanField(blank=True, null=True, unique=True),
        ),
    ]
