# Generated by Django 2.2.11 on 2020-03-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_cohort_is_sample'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graph',
            options={'ordering': ('order',)},
        ),
    ]
