# Generated by Django 2.2.12 on 2020-04-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20200317_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graph',
            options={'ordering': ('topic__cohort', 'order')},
        ),
    ]
