# Generated by Django 2.2.19 on 2021-03-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_auto_20210309_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='n_name',
            field=models.TextField(default='N'),
        ),
    ]
