# Generated by Django 2.2.19 on 2021-04-05 19:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_graph_n_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='line_4_dashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_4_label',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_4_offset_x',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_4_offset_y',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_4_slope',
            field=models.DecimalField(decimal_places=4, default=Decimal('-1'), max_digits=12),
        ),
    ]
