# Generated by Django 2.2.20 on 2021-04-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_auto_20210405_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='x_axis_2_label',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='y_axis_2_label',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
