# Generated by Django 3.2.17 on 2023-02-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_assignment_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='adaptive',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ap_correct',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ap_incorrect',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_assessment',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_key',
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adaptive', models.BooleanField(default=False)),
                ('is_assessment', models.BooleanField(default=True)),
                ('title', models.TextField(default='Untitled', max_length=1024)),
                ('ap_correct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_continue', to='main.questionbank')),
                ('ap_incorrect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_intervene', to='main.questionbank')),
                ('questions', models.ManyToManyField(blank=True, to='main.Question')),
                ('supplemental', models.ManyToManyField(blank=True, related_name='_main_questionbank_supplemental_+', to='main.QuestionBank')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='banks',
            field=models.ManyToManyField(blank=True, to='main.QuestionBank'),
        ),
    ]
