# Generated by Django 3.2.17 on 2023-02-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_auto_20230202_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
