# Generated by Django 3.2.18 on 2023-02-17 18:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_auto_20230217_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='banks',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='is_assessment',
        ),
        migrations.AddField(
            model_name='question',
            name='assessment_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.assessmentrule'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='description',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
