# Generated by Django 3.2.18 on 2023-02-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_auto_20230217_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionbank',
            options={'ordering': ('assignment', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='questionbank',
            unique_together={('title', 'assignment')},
        ),
    ]
