# Generated by Django 3.2.18 on 2023-02-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_auto_20230221_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='supplemental',
            field=models.ManyToManyField(blank=True, to='main.QuestionBank'),
        ),
    ]
