# Generated by Django 3.2.18 on 2023-03-16 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_auto_20230314_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='partial',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='value',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionevaluation',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='questionevaluation',
            name='user_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userassignment'),
        ),
        migrations.AlterUniqueTogether(
            name='questionevaluation',
            unique_together={('question', 'user_assignment')},
        ),
        migrations.RemoveField(
            model_name='questionevaluation',
            name='assessment_rule',
        ),
    ]
