# Generated by Django 3.2.18 on 2023-03-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_auto_20230316_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionevaluation',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='questionevaluation',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
