# Generated by Django 3.2.19 on 2023-05-08 17:13

from django.db import migrations, models
import econplayground.main.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_question_media_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='media_upload',
            field=models.FileField(blank=True, null=True, storage=econplayground.main.custom_storage.MediaStorage, upload_to=''),
        ),
    ]
