# Generated by Django 3.2.18 on 2023-03-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_auto_20230320_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='a',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='a1',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='a1_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='a2',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='a2_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='a3',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='a3_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='a4',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='a4_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='a5',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='alpha',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='area_a_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='area_b_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='area_c_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='cobb_douglas_a',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='cobb_douglas_a_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='cobb_douglas_alpha',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='cobb_douglas_alpha_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='cobb_douglas_k',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='cobb_douglas_k_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='cobb_douglas_l',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='cobb_douglas_l_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='cobb_douglas_y_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='function_choice',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='intersection_2_horiz_line_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='intersection_2_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='intersection_2_vert_line_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='intersection_3_horiz_line_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='intersection_3_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='intersection_3_vert_line_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='intersection_horiz_line_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='intersection_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='intersection_vert_line_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='k',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='question',
            name='line_1_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='line_1_offset_x',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='line_1_offset_y',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='line_1_slope',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='line_2_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='line_2_offset_x',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='line_2_offset_y',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='line_2_slope',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='line_3_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='line_3_offset_x',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='line_3_offset_y',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='line_3_slope',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='line_4_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='line_4_offset_x',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='line_4_offset_y',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='line_4_slope',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='n_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='omega',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='r',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='x_axis_2_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='x_axis_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='y1',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='y2',
            field=models.IntegerField(choices=[(-1, 'Negative'), (0, 'None'), (1, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='y_axis_2_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='y_axis_label',
            field=models.BooleanField(default=False),
        ),
    ]
