# Generated by Django 3.2.18 on 2023-03-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_auto_20230328_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='keywords',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='questionevaluation',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
