# Generated by Django 4.2.2 on 2023-06-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_alter_question_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='graph',
        ),
    ]
