# Generated by Django 4.2.2 on 2023-06-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_remove_question_graph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='cohorts',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='instructor',
        ),
    ]
