# Generated by Django 4.2.10 on 2024-02-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_alter_evaluation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='assignment_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Template'), (1, 'Labeling'), (2, 'Modification')], default=0),
        ),
        migrations.AlterField(
            model_name='graph',
            name='graph_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Linear Demand and Supply'), (1, 'Input Markets'), (3, 'Cobb-Douglas Production Graph'), (5, 'Consumption-Leisure: Constraint'), (7, 'Consumption-Saving: Constraint'), (8, 'Linear Demand and Supply: 3 Functions'), (9, 'Linear Demand and Supply: Areas'), (10, 'Input Markets: Areas'), (11, 'Consumption-Saving: Optimal Choice'), (15, 'Consumption-Leisure: Optimal Choice'), (12, 'Input-Output Illustrations'), (13, 'Linear Demand and Supply: 2 Diagrams'), (14, 'Input Markets: 2 Diagrams'), (16, 'Template Graph')], default=0),
        ),
    ]
