# Generated by Django 4.2.11 on 2024-03-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_alter_graph_assignment_type_alter_graph_graph_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='expression',
            field=models.TextField(blank=True, default='x'),
        ),
    ]
