# Generated by Django 4.2.11 on 2024-04-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_graph_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='expression_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='graph',
            name='expression_3',
            field=models.TextField(blank=True, default=''),
        ),
    ]
