# Generated by Django 4.2.13 on 2024-06-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_graph_a1_max_graph_a1_min_graph_a2_max_graph_a2_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='x_axis_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graph',
            name='y_axis_min',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
