# Generated by Django 4.2.13 on 2024-06-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_alter_graph_graph_type'),
        ('main', '0108_graph_major_grid_type_graph_minor_grid_type'),
    ]

    operations = [
    ]
