# Generated by Django 4.2.14 on 2024-07-24 20:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_graph_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='a6',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='a7',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='a8',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
    ]
