# Generated by Django 4.2.14 on 2024-07-26 18:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_graph_a6_graph_a7_graph_a8'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='a1_2',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='a1_max_2',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='graph',
            name='a1_min_2',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='a2_2',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='a2_max_2',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='graph',
            name='a2_min_2',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='a3_2',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='a3_max_2',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='graph',
            name='a3_min_2',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='a4_2',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='a4_max_2',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='graph',
            name='a4_min_2',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='a5_2',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='a5_max_2',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='graph',
            name='a5_min_2',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='graph',
            name='x_axis_max_2',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='graph',
            name='x_axis_min_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graph',
            name='y_axis_max_2',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='graph',
            name='y_axis_min_2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
