# Generated by Django 4.2.14 on 2024-07-26 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0115_graph_a1_2_graph_a1_max_2_graph_a1_min_2_graph_a2_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='a1_max_2',
            new_name='a1_2_max',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='a1_min_2',
            new_name='a1_2_min',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='a2_max_2',
            new_name='a2_2_max',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='a2_min_2',
            new_name='a2_2_min',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='a3_max_2',
            new_name='a3_2_max',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='a3_min_2',
            new_name='a3_2_min',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='a4_max_2',
            new_name='a4_2_max',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='a4_min_2',
            new_name='a4_2_min',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='a5_max_2',
            new_name='a5_2_max',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='a5_min_2',
            new_name='a5_2_min',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='x_axis_max_2',
            new_name='x_axis_2_max',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='x_axis_min_2',
            new_name='x_axis_2_min',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='y_axis_max_2',
            new_name='y_axis_2_max',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='y_axis_min_2',
            new_name='y_axis_2_min',
        ),
    ]
