# Generated by Django 4.2.14 on 2024-07-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0115_graph_a1_2_graph_a1_max_2_graph_a1_min_2_graph_a2_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='a5_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
