# Generated by Django 4.2.15 on 2024-08-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0119_alter_graph_graph_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='alpha',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='omega',
        ),
    ]
