# Generated by Django 4.2.15 on 2024-08-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_alter_graph_graph_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='a1_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a1_max_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a1_min_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a2_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a2_max_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a2_min_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a3_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a3_max_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a3_min_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a4_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a4_max_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a4_min_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a5_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a5_max_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='a5_min_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='x_axis_max_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='x_axis_min_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='y_axis_max_2',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='y_axis_min_2',
        ),
    ]
