# Generated by Django 5.1.8 on 2025-04-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0126_cohort_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='context_id',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='cohort',
            name='deployment_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
