# Generated by Django 5.2.1 on 2025-05-29 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0127_cohort_context_id_cohort_deployment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='feedback_fulfilled',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='feedback_unfulfilled',
        ),
    ]
