# Generated by Django 5.2.3 on 2025-07-02 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0128_remove_submission_feedback_fulfilled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='students',
            field=models.ManyToManyField(related_name='courses_enrolled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='instructors',
            field=models.ManyToManyField(related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
    ]
