# Generated by Django 5.2.4 on 2025-07-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0130_alter_cohort_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jxglinetransformation',
            name='line',
        ),
        migrations.DeleteModel(
            name='JXGLine',
        ),
        migrations.DeleteModel(
            name='JXGLineTransformation',
        ),
    ]
